Changed error(error) to error(e) as Nuxt crashes with `error is not a function` message (#893)
The error message is
```
 ERROR  error is not a function                                                                                                                  02:53:10
  at asyncData (_id.vue:24:0)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (internal/process/task_queues.js:93:5)
» Updated pages\posts\_id.vue
```

The error message there is in the catch block. the code is trying to call error, but it has just overwritten that error parameter in the asyncData with the error variable in the catch block. 
So the code is overwriting the error variable that it got from deconstructuring when it declared the same variable name error for the catched error variable

Co-authored-by: Sébastien Chopin <seb@nuxtjs.com>